kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    environment:
      COVID_HASURA_DOMAIN:
        from_secret: covid_hasura_domain
      COVID_ION_TOKEN:
        from_secret: covid_ion_token
      COVID_MAPBOX_TOKEN:
        from_secret: covid_mapbox_token
    settings:
      repo: xgis/covid-web
      tags: [ "${DRONE_COMMIT_SHA:0:7}", "latest" ]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args_from_env:
        - COVID_HASURA_DOMAIN
        - COVID_ION_TOKEN
        - COVID_MAPBOX_TOKEN

trigger:
  branch:
  - main
