kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    environment:
      COVID_HASURA_DOMAIN:
        from_secret: covid_hasura_domain
      COVID_ION_TOKEN:
        from_secret: covid_ion_token
      COVID_MAPBOX_TOKEN:
        from_secret: covid_mapbox_token
    settings:
      repo: xgis/covid-web
      tags: [ "${DRONE_COMMIT_SHA:0:7}", "latest" ]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args_from_env:
        - COVID_HASURA_DOMAIN
        - COVID_ION_TOKEN
        - COVID_MAPBOX_TOKEN
  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl -n=covid apply -f deployment.yaml
      - kubectl -n=covid patch deployment covid-web -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"

clone:
  skip_verify: true
